import psycopg
import json
import re

# Regex for GPA
gpa_re = re.compile("(\A\d?\.\d+\z|\A\d\z)")

# Create table in database to hold applicant info
def create_table(dbname, user, password):

     # Connect to database
     connection = psycopg.connect(dbname = dbname, 
                                  user = user, 
                                  password = password)
     with connection.cursor() as c:
          c.execute("""
                    CREATE TABLE results(
                         p_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         program text,
                         comments text,
                         date_added date,
                         url text,
                         status text,
                         term text,
                         us_or_international text,
                         gpa float,
                         gre float,
                         gre_v float,
                         gre_aw float,
                         degree text,
                         llm_generated_program text,
                         llm_generated_university text
                    );
                    """)
          
          connection.commit()
          c.close()
          connection.close()
     
# Load data from file into database
def load_data(dbname, user, password):

     # Connect to database
     connection = psycopg.connect(dbname = dbname, 
                                  user = user, 
                                  password = password)
     
     with connection.cursor() as c:
          
          # Read file with entries for database
          with open("llm_extend_applicant_data.json", "r", ) as f:
               applicant_data = json.loads(f.read())

          # Empty query string
          query = ""
          
          # Format each entry in file as json object, append to query string
          for json_object in applicant_data:
                    if json_object["gpa"] == "":
                         json_object["gpa"] = "NULL"

                    if gpa_re.match(json_object["gpa"]) is None:
                         json_object["gpa"] = "NULL"

                    if json_object["gre"] == "":
                         json_object["gre"] = "NULL"

                    if json_object["gre v"] == "":
                         json_object["gre v"] = "NULL"

                    if json_object["gre aw"] == "":
                         json_object["gre aw"] = "NULL"

                    query += f"INSERT INTO results \
                    VALUES (DEFAULT,\
                    '{json_object["program"].replace("'", "''")}', \
                    '{json_object["comments"].replace("'", "''")}',\
                    '{json_object["date_added"].replace("'", "''")}',\
                    '{json_object["url"].replace("'", "''")}',\
                    '{json_object["status"].replace("'", "''")}',\
                    '{json_object["term"].replace("'", "''")}',\
                    '{json_object["US/International"].replace("'", "''")}',\
                    {json_object["gpa"].replace("'", "''")},\
                    {json_object["gre"].replace("'", "''")},\
                    {json_object["gre v"].replace("'", "''")},\
                    {json_object["gre aw"].replace("'", "''")},\
                    '{json_object["degree"].replace("'", "''")}',\
                    '{json_object["llm-generated-program"].replace("'", "''")}',\
                    '{json_object["llm-generated-university"].replace("'", "''")}');"
                    
          # Execute query string and close connections
          c.execute(query)
          connection.commit()
     c.close()
     connection.close()
     