import psycopg
import json

connection = psycopg.connect(dbname = "applicants", user = "postgres")

with connection.cursor() as c:

    c.execute("""
            CREATE TABLE results(
              p_id int GENERATED BY DEFAULT AS IDENTIY PRIMARY KEY
              program text
              comments text
              date_added date
              url text
              status text
              term text
              us_or_international text
              gpa float
              gre float
              gre_v float
              gre_aw float
              degree text
              llm_generated_program text
              llm_generated_university text
            );
            """)
    
    with open("llm_extend_applicant_data.json", "r") as f:
        applicant_data = json.loads(f.read())

    query = ""
    
    for json_object in applicant_data:
            query += f"INSERT('{json_object["program"]}', \
            '{json_object["comments"]}',\
            '{json_object["date_added"]}',\
            '{json_object["url"]}',\
            '{json_object["status"]}',\
            '{json_object["term"]}',\
            '{json_object["US/International"]}',\
            {json_object["gpa"]},\
            {json_object["gre"]},\
            {json_object["gre v"]},\
            {json_object["gre aw"]},\
            '{json_object["degree"]}',\
            '{json_object["llm_generated_program"]}'\
            '{json_object["llm_generated_university"]}')"
    
    c.execute(query)